package com.innoprog.android.util

enum class ErrorType {
    NO_CONNECTION,
    NOT_FOUND,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    CONFLICT,
    UNEXPECTED,
    UNPROCESSABLE_ENTITY,
    INTERNAL_SERVER_ERROR,
    BAD_GATEWAY,
    CAPTCHA_REQUIRED,
    UNKNOWN_ERROR
}
